import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ArtProvider } from "@/context/artContext";
import { SndProvider } from "@/context/secondContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased min-h-full flex flex-col text-black bg-white`}
    >
      <body className="min-h-full flex flex-col  text-black bg-white">
        <SndProvider>

          <ArtProvider>

            {children}

          </ArtProvider>
        </SndProvider>


      </body>
    </html>
  );
}
